import 'core-js/es/symbol'
import 'core-js/es/symbol/iterator'
import 'core-js/es/promise'
import 'core-js/es/object/assign'
import 'core-js/es/array/includes'
import 'core-js/es/map'
import 'core-js/es/set'
import 'whatwg-fetch'
